### ISSUE TITLE
Wrong conversion with &nbsp;

### ISSUE THREAD

**Issue by ricaragao** [remarkablemark/html-react-parser#147] opened 2020-04-02 02:23 UTC
When I try parse some string with `&nbsp;` it show a wrong character: `

- Version: 0.9.1
- Platform: all
- Browser: all

**Comment by remarkablemark** [comment] 2020-04-02 02:26
Can you provide a reproducible example using [Repl.it](https://repl.it/@remarkablemark/html-react-parser) or [JSFiddle](https://jsfiddle.net/remarkablemark/7v86d800/)?

**Comment by remarkablemark** [comment] 2020-04-19 18:02
Closing issue as I'm unable to reproduce this:

- [Node.js](https://repl.it/@remarkablemark/html-react-parser-147-1)
- [Web](https://repl.it/@remarkablemark/html-react-parser-147-2)

**Closed by remarkablemark** 2020-04-19 18:02 UTC

**Comment by ricaragao** [comment] 2020-04-19 18:11
@remarkablemark , sorry for late feedback. The problem was with font file and not with html-react-parser.
