### ISSUE TITLE
Strangely adding a 141% padding-bottom to an inserted <div> upon rendering.

### ISSUE THREAD

**Issue by jshuadvd** [remarkablemark/html-react-parser#38] opened 2017-05-27 21:13 UTC
Hi there! Awesome module. Everything is working flawlessly, with the exception of one thing. I am parsing `<iframe>` with this. It suits my needs fine with a single exception thus far. When I parse an  `<iframe>` from a Google Doc or something similar the module is automatically inserting a `padding-bottom: 141.423%` to the element in question. I can hack this with CSS by targeting my parent class of `.message-unfurl div { }` but that effects other things. I tried looking into my `node_modules` folder to see if i could just hardcode it in the `return` there, but did not see the code for that. Any help would be greatly appreciated. I have added an image below of the selected element. Thank you!

[http://imgur.com/a/CaYFd](http://imgur.com/a/CaYFd)

**Comment by remarkablemark** [comment] 2017-05-28 01:12
@jshuadvd Would you mind providing some sample code so I can reproduce this bug? I ask this because I find it strange that it would be doing this.

Feel free to use the fiddle: http://jsfiddle.net/remarkablemark/kogm4gjp/

**Comment by remarkablemark** [comment] 2017-06-09 23:35
It seems like the issue is coming from the HTML itself:

![screenshot](https://user-images.githubusercontent.com/10594555/26997758-52daefd0-4d4a-11e7-9784-23fd8dcaeef6.png)

Once you remove the declaration, it should be good (see [fiddle](http://jsfiddle.net/remarkablemark/kogm4gjp/2/)).

Does this resolve your problem @jshuadvd?

**Comment by jshuadvd** [comment] 2017-06-13 08:22
Hmm. Yes I am not sure where that is coming from. It seems to be when it is injected into the Parser it is being added. I can remove that declaration in the dev tools, but not in the app.

**Comment by remarkablemark** [comment] 2017-06-17 21:03
Since the issue is coming from the app and not the parser, then I'm unsure what can be done on my end.

Perhaps the [replace](https://github.com/remarkablemark/html-react-parser#replacedomnode) option can help you out? Otherwise, I will be closing the issue then.

**Closed by remarkablemark** 2017-06-17 21:03 UTC
