### ISSUE TITLE
TS Error: This expression is not callable

### ISSUE THREAD

**Issue by thany** [remarkablemark/html-react-parser#975] opened 2023-07-06 14:36 UTC
## Expected Behavior

Expression is callable according to TS, ergo, no errors.

## Actual Behavior

A TS error appears when calling:

```typescript
import parse from 'html-react-parser';

parse('<b>foo</b>');
```

Error:
```
This expression is not callable.
  Type 'typeof import("c:/Projects/.../node_modules/html-react-parser/index")' has no call signatures.
ts(2349)
```

## Steps to Reproduce

Checkout the repro below, do a `npm i` on it, and open it in VScode. This should display the error:

![image](https://github.com/remarkablemark/html-react-parser/assets/152227/bc07e763-5748-4820-8c30-55e59bef32d9)

Maybe running `tsc` on it will give the same error - I haven't tried it.

## Reproducible Demo

https://github.com/thany/html-react-parser-error

Please note: Yes, `"moduleResolution": "node"` will fix it, but that will cause other problems. It has to be set to `nodenext` and cannot be anything else, unfortunately.

## Environment

- Version: 4.0.0
- Platform: Typescript I guess?
- Browser: N/A
- OS: Windows 10

## Keywords

typescript import default error

**Comment by thany** [comment] 2023-07-06 14:44
Please note, the code **works at runtime** which means there's only something wrong with the typings.

Also, as sometimes suggested on SO and the likes, this will not work:

```typescript
const parsed = parse.default('<b>yolo</b>');
```

Because, again, it already worked at runtime, and this breaks it at runtime, because at runtime the `.default` isn't there.

There is another workaround that only works because Typescript allows it:

```typescript
const parsed = (parse as unknown as typeof parse.default)('<b>yolo</b>');
```

But this is just as silly as all the sillyness of sillynesses 🙂
However, it does illustrate that *Typescript* wants the `parse.default` notation, while its own resulting *Javascript* output wants the regular notation 🤨

It's also worth noting that the actual project, not the small repro-repo, contains a multitude more packages, both internal and from node_modules, and they all work fine, with default imports and named imports alike.

**Comment by remarkablemark** [comment] 2023-07-06 15:22
@thany what TypeScript version are you using?

**Comment by thany** [comment] 2023-07-06 15:28
In the repro, I added the same typescript version as the one in our proper project, which is 4.9.3.

**Comment by remarkablemark** [comment] 2023-07-06 16:13
Thanks, I'll try to check it out later tonight when I have some time

**Comment by thany** [comment] 2023-07-06 17:17
Cool. No hurry though, because we do have that silly workaround for the time being 🙂

And if it comes to upgrading typescript, well, that's due anyway, but somehow I doubt it's the root cause. I can certainly give it a go though.

**Comment by remarkablemark** [comment] 2023-07-07 00:06
@thany I cloned the [repository](https://github.com/thany/html-react-parser-error) that you created and I can confirm that I'm seeing your error. I wonder if this is caused by the [ESM export](https://github.com/remarkablemark/html-react-parser/blob/master/index.mjs).

I do want to note that this does work for me even after building and running the built code:

```ts
const parsed = parse.default('<b>yolo</b>');
```

What is the runtime error that you're experiencing?

**Comment by thany** [comment] 2023-07-07 19:44
Oh for me `parse()` worked fine at runtime but `parse.default()` just straight up didn't exist, so I got an error along the lines of "...is not a function" (sorry, it's the weekend now, I'm not at my work pc and enjoying a beer, so I don't remember the exact wording 🙂).

Even so, I don't think it's normal to be having to use that syntax, even if it did work. Unfortunately, packaging and exports and all that, combined with the plethora of configuration options and a sprinkle of typescript, is pure magic to me. Therefore I can't be too sure what other packages are doing differently where a default export works exactly as per their documentation. 

One such package is axios, but there are many more.

**Comment by remarkablemark** [comment] 2023-07-07 19:54
Gotcha @thany, I'll see if I can look into this some more or fork your repo to try things. Have a great weekend!

**Comment by remarkablemark** [comment] 2023-07-22 01:07
@thany I have a PR in which I encountered no build errors with `parse.default`: https://github.com/remarkablemark/html-react-parser-error-975/pull/1

**Comment by thany** [comment] 2023-07-24 12:12
Yeah. I dunno what happened. It works for me as well. Something must've changed in the mean time 🤨

But I do still have to use `parse.default` whereas `parse` is still not a callable expression. Again, it works fine at runtime, but TS complains that it's not a callable expression. Surely you too saw this when trying to compile the repro.

Your typings must be wrong then I guess, even though the implementation works as documented. Although my knowledge of `.d.ts` files is not extensive enough to see how they would be wrong. It looks fine at a glance.

**Comment by thany** [comment] 2023-07-24 15:11
Meanwhile, I've managed to change your repo in a fork, to have modern imports and exports everywhere, amking it "just work" (in my scenario).

Imports/exports is definitely among "the bad parts" of javascript, sjeez. Anyway, here it is:
https://github.com/thany/html-react-parser

I had to do a few more improvements on the side to get everything working again, because of course the unittests are quite rigorous, which is good, but it was quite a pain to figure them out.

Lemme know if you'd like a PR.

**Comment by thany** [comment] 2023-07-24 18:55
Yeah I thought so. Even so, feel free to use (parts of) it to modernise your branch.

**Comment by remarkablemark** [comment] 2023-07-24 19:34
Thanks!

**Comment by remarkablemark** [comment] 2023-08-11 18:35
Closing this issue since we'll be migrating to TypeScript in #1000

**Closed by remarkablemark** 2023-08-11 18:35 UTC
Labels: question
