### ISSUE TITLE
Running the parser in a vercel edge function

### ISSUE THREAD

**Issue by sylvesteraswin** [remarkablemark/html-react-parser#736] opened 2022-10-30 18:38 UTC
Hello,

Is it possible to run the parser in an edge function? I am trying to convert static HTML string to a react object in a vercel edge function.

Thanks
Sylvester

**Comment by remarkablemark** [comment] 2022-10-30 19:09
@sylvesteraswin Yes, it should be possible since this library can be run on both the server and client-side. See [Node.js demo](https://replit.com/@remarkablemark/html-react-parser).

**Comment by sylvesteraswin** [comment] 2022-10-30 21:59
@remarkablemark thanks for your quick reply, I am referring to [Vercel Edge functions](https://vercel.com/docs/concepts/functions/edge-functions/edge-functions-api). Looks like it does not support most of the Node.JS APIs.

Here is my example

```tsx
// /api/sample.tsx

export const config = {
  runtime: "experimental-edge",
};

const handler = async (req: NextRequest) => {
  const element = reactParser(`<html></html>`, {});

  return element;
}

export default handler;
```


This is the below error I get

```bash
[Error: This browser does not support `document.implementation.createHTMLDocument`]
```

**Comment by remarkablemark** [comment] 2022-10-31 03:15
Thanks for the response. It seems like Vercel Edge functions is using the `browser` field of [html-dom-parser](https://github.com/remarkablemark/html-dom-parser/blob/v3.1.2/package.json#L88-L91), which is causing this error. If it didn't try to load the client library, I believe it should work.

**Comment by Jahrhause** [comment] 2022-10-31 13:59
I am also facing this issue, but just using server-side components in Next.js 13 :(

```
import parse from 'html-react-parser';

const htmlFromCMS = '<p>testing</p>';

...

return (
      <div>
        {parse(htmlFromCMS)}
      </div>
    );
```

returns:

```
Warning: Only createServerContext is supported in Server Components.
Error: This browser does not support `document.implementation.createHTMLDocument`
    at parseFromDocument (webpack-internal:///(sc_server)/./node_modules/html-dom-parser/lib/client/domparser.js:12:11)
    at domparser (webpack-internal:///(sc_server)/./node_modules/html-dom-parser/lib/client/domparser.js:124:23)
    at HTMLDOMParser (webpack-internal:///(sc_server)/./node_modules/html-dom-parser/lib/client/html-to-dom.js:24:22)
    at HTMLReactParser (webpack-internal:///(sc_server)/./node_modules/html-react-parser/index.js:27:23)
    at Textblock (webpack-internal:///(sc_server)/./src/components/modules/Textblock.tsx:109:79)
    at attemptResolveElement (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1167:42)
    at attemptResolveElement (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1211:48)
    at retryTask (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1811:43)
    at performWork (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1856:33)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1257:40)
    at scheduleWork (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:52:25)
    at pingTask (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1256:29)
    at ping (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js:1269:40)
```

**Comment by remarkablemark** [comment] 2022-10-31 16:10
@Jahrhause do you have a custom webpack config?

**Comment by Jahrhause** [comment] 2022-11-02 15:13
@remarkablemark ahh that fixed the issue, sorry about that :)

**Comment by garrrikkotua** [comment] 2022-11-03 13:06
Hey! I have the same problem in Vercel Edge Functions, though I have default webpack config (Next.js 13).

`Error: This browser does not support document.implementation.createHTMLDocument`

In the logs I see it calls the `lib\cleint` instead of `lib\server`. Any ideas how to solve it? Can I somehow call the server implementatiion directly?

Thanks!

**Comment by grantmagdanz** [comment] 2023-06-21 04:35
Running into this as well. I'm using Vercel's og image library (which runs in vercel edge functions) to generate OG images for rich text posts. I'd like to use this library to turn HTML into JSX and use it in the og image.

Here is a github repo you can use to reproduce. It's pretty simple:

- run `pnpm install`
- run `pnpm dev`
- navigate to `localhost:3000/api/og`

You should run into it every time.

**Comment by JunkyDeLuxe** [comment] 2023-06-28 07:45
I confirm this issues still exists and it's can be a hudge problem, because if the error popup 
Error: This browser does not support `document.implementation.createHTMLDocument`
The page in nextjs is fully loaded by the browser, SSR will break because of that.
I did that in order to fix the problem but now I have a hydrating error

```
'use client';

import { isServer } from '@/helpers/utils/isServer';
import parse from 'html-react-parser';

const DisplayHtmlContent: React.FC<{ content }> = ({ content }) => {
	if (isServer()) {
		return <div>{content}</div>;
	}

	return <div>{parse(content)}</div>;
};

export default DisplayHtmlContent;
```

**Comment by remarkablemark** [comment] 2023-06-28 15:30
This may be an issue on Vercel since it seems to be using the browser module of `html-dom-parser` on the server-side, which is causing this error. Has anyone tried opening an issue on Vercel?

**Comment by remarkablemark** [comment] 2023-06-28 15:31
@grantmagdanz can you share the link to your GitHub repo?

**Comment by grantmagdanz** [comment] 2023-06-28 15:53
Oh sorry here it is: https://github.com/grantmagdanz/vercel-og-nextjs

**Comment by remarkablemark** [comment] 2023-06-29 02:57
@grantmagdanz I was able to fix the server error by updating the Webpack config in `next.config.js`:

```js
const path = require('path');

/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  webpack: (config) => {
    config.module.rules = [
      ...config.module.rules,
      {
        test: /html-react-parser\/index\.js$/,
        resolve: {
          alias: {
            'html-dom-parser': path.join(path.dirname(require.resolve('html-dom-parser')), 'lib/server/html-to-dom.js'),
          },
        },
      },
    ];
    return config;
  },
}
```

See https://github.com/remarkablemark/vercel-og-nextjs/pull/2

**Comment by remarkablemark** [comment] 2023-06-29 02:59
Given this server error seems to be coming from Vercel/Webpack/PNPM and not from this library, I'm going to close this issue as won't do.

**Closed by remarkablemark** 2023-06-29 02:59 UTC
Labels: question, wontfix

**Comment by j4tmr** [comment] 2024-03-27 07:23
@remarkablemark It seems that the solution that was effective before now no longer works. First, I updated to the latest version, 5.1.9. Also, I noticed that the path you used, path.join(path.dirname(require.resolve('html-dom-parser')), 'lib/server/html-to-dom.js'), results in **/node_modules/html-dom-parser/lib/lib/server/html-to-dom.js, so I removed one layer of /lib, but it still doesn't work. Do you have any new ideas?

**Comment by remarkablemark** [comment] 2024-03-27 15:50
@j4tmr try this:

```js
path.join(path.dirname(require.resolve('html-dom-parser')), 'server/html-to-dom.js')
```

**Comment by j4tmr** [comment] 2024-03-29 07:15
@remarkablemark I think it's not because of the URL issue; I corrected the URL, and yet, it still reports, `Error: This browser does not support document.implementation.createHTMLDocument`.

**Comment by remarkablemark** [comment] 2024-03-29 16:12
@j4tmr can you open `node_modules/html-dom-parser` in your IDE and verify the full path to `server/html-to-dom.js`? You can copy that path and update in your webpack config

**Comment by j4tmr** [comment] 2024-04-08 06:26
@remarkablemark Thank you for your reply. I tested it again today, and my webpack code is like this. 
```
webpack: (config) => {
    console.log(path.join(path.dirname(require.resolve('html-dom-parser')), 'server/html-to-dom.js'))
    config.module.rules = [
      ...config.module.rules,
      {
        test: /html-react-parser\/index\.js$/,
        resolve: {
          alias: {
            'html-dom-parser': path.join(path.dirname(require.resolve('html-dom-parser')), 'server/html-to-dom.js'),
          },
        },
      },
    ];
    return config;
  },
```
I console.logged the URL, and the result looks like this. `/Users/UserName/VSCode/ProjectName/node_modules/html-dom-parser/lib/server/html-to-dom.js` I am sure that I can directly access the file via this URL. On a Mac's VSCode, you can just use command + click. I tested using a relative URL or pasting the URL directly without using path, and the result was the same.

**Comment by j4tmr** [comment] 2024-04-08 07:33
@remarkablemark 
I changed `test: /html-react-parser\/index\.js$/` to `test: /html-react-parser\/lib\/index\.js$/` it worked.

**Comment by sampotts** [comment] 2024-12-18 13:05
Has anyone got this workaround working using turbopack?
