### ISSUE TITLE
React passing variables throws "parse is not a function"

### ISSUE THREAD

**Issue by salicius** [remarkablemark/html-react-parser#948] opened 2023-06-07 10:04 UTC
## Expected Behavior
It should render my variables with html tags inside 

## Actual Behavior
it throws the error "parse is not a function"

## Steps to Reproduce

I have this code. I tried this two ways but, they don't works.

```javascript
export default function MyList() {
  const parse = require("html-react-parser");

  const items= [
    { number: "1.", text: `Click on <strong>DOWNLOAD</strong>` },
    { number: "2.", text: `Allow download` },
    { number: "3.", text: `Once the download is complete, click on <strong>open</strong>` },
  ];

return (
    <List>
        {items.map((item, index) => {
          return (
            <ListItem key={index}>
               <Typography>{parse(item.text)}</Typography>
               <Typography>{parse(`${item.text}`)}</Typography>
            </ListItem>
           );
        })}
    </List>
    );
}
```

## Environment

- Version:
- Platform:
- Browser:
- OS:

**Comment by salicius** [comment] 2023-06-07 10:09
Ok, i solved by using function import:
`import parse from 'html-react-parser';`  
instead using the:
`const parse = require("html-react-parser");`

maybe it s a bug of the require function ?

**Comment by remarkablemark** [comment] 2023-06-07 15:22
Hmm that seems strange. I wonder if it has something to do with your configuration. I just checked the [Replit](https://replit.com/@remarkablemark/html-react-parser) and I can't seem to reproduce it.

**Comment by remarkablemark** [comment] 2023-06-07 15:23
Closing since I cannot reproduce it

**Closed as completed by remarkablemark** 2023-06-07 15:23 UTC
Labels: invalid
