### ISSUE TITLE
`parse` not not working with bulleted items

### ISSUE THREAD

**Issue by isaacdarcilla** [remarkablemark/html-react-parser#1021] opened 2023-08-21 22:52 UTC
## Expected Behavior

It should display bullets.

## Actual Behavior

Does not parse bulleted items.

## Steps to Reproduce

Parse this html content.

```html
<div class="copy-heading">
<h2 id="wsl"><span class="copy-title" style="background-color: rgb(45, 194, 107); color: rgb(241, 196, 15);">WSL</span></h2>
</div>
<p>PhpStorm will now support developing in a&nbsp;<a href="https://docs.microsoft.com/en-us/windows/wsl/about" target="_blank" rel="noopener">WSL</a>&nbsp;(Windows Subsystem for Linux) environment, which is when you have launched your IDE on a Windows 10 machine, but you target WSL/Linux in your development. You&rsquo;ll be able to specify a remote PHP interpreter in the WSL and use it for running scripts, tests, Composer commands, and debugging.</p>
<ul>
<li>To get started, make sure you have installed the WSL on your Windows 10 machine, and the Linux distribution of your choice. See the&nbsp;<a href="https://docs.microsoft.com/en-us/windows/wsl/install-win10" target="_blank" rel="noopener">installation guide</a>.</li>
<li>Depending on the distribution you may have PHP already preinstalled. If not, you&rsquo;ll have to install it manually via the command line. For example in Ubuntu you can run something like this:<br><code>sudo apt update<br>sudo apt install php php-mbstring php-dom php-xml php-zip php-curl php-xdebug</code></li>
<li>When you have PHP in your WSL environment you&rsquo;re ready to set up PhpStorm.</li>
<li>Add a CLI interpreter under File | Settings | Languages &amp; Frameworks | PHP</li>
</ul>
```

Screenshot of the parsed html content

![image](https://github.com/remarkablemark/html-react-parser/assets/22732118/90ff5e00-15e4-4f6c-92dd-a860c1b30431)

**Comment by remarkablemark** [comment] 2023-08-21 22:56
@isaacdarcilla it works correctly in [CodeSandbox](https://codesandbox.io/s/html-react-parser-1021-rmlcky) and I'm unable to reproduce your issue.

**Comment by isaacdarcilla** [comment] 2023-08-21 23:39
```js
 <div className="mt-3">{parse(packageData.description)}</div>
 ```
 
 This is the parent element.

**Comment by remarkablemark** [comment] 2023-08-21 23:44
@isaacdarcilla it still works after adjusting with your parent element: https://codesandbox.io/s/html-react-parser-1021-rmlcky?file=/src/index.tsx

**Comment by remarkablemark** [comment] 2023-11-10 17:42
Closing as won't do

**Closed by remarkablemark** 2023-11-10 17:42 UTC
Labels: invalid
