### ISSUE TITLE
A component is `contentEditable` and contains `children` managed by React warning

### ISSUE THREAD

**Issue by wangfulong** [remarkablemark/html-react-parser#140] opened 2020-02-28 08:26 UTC
```
  const options = {
    replace: (root) => {
      const { attribs, children, name, type } = root;
      //Remove your contenteditable attribute from your htmlstring, 
      //Otherwise, an error will be reported when react render
      if (attribs && attribs.contenteditable) {
        delete attribs.contenteditable;
      }
    }
  };
```

**Comment by remarkablemark** [comment] 2020-02-28 18:08
Thanks for opening this issue @wangfulong

Do you mind creating a reproducible example? (You can pick one of the code playgrounds [here](https://github.com/remarkablemark/html-react-parser#example).)

**Comment by wangfulong** [comment] 2020-03-01 04:38
> Thanks for opening this issue @wangfulong
> 
> Do you mind creating a reproducible example? (You can pick one of the code playgrounds [here](https://github.com/remarkablemark/html-react-parser#example).)

I get this html string from quill, after insert mention 

const htmlstring =`<p><span class="mention" data-index="0" data-denotation-char="@" data-id="all" data-value="所有人">﻿<span contenteditable="false"><span class="ql-mention-denotation-char">@</span>所有人</span>﻿</span> <span class="mention" data-index="1" data-denotation-char="@" data-id="qDJs5nJeXhvTNQroq" data-value="测试101">﻿<span contenteditable="false"><span class="ql-mention-denotation-char">@</span>测试101</span>﻿</span> </p>`

**Comment by remarkablemark** [comment] 2020-03-04 01:02
Thanks for providing an HTML string that reproduces this warning. I was able to reproduce it in this [fiddle](https://jsfiddle.net/remarkablemark/53oLfmap/).

It turns out this is expected behavior. React will throw a **_warning_** (not _error_) when an element has an `contentEditable` attribute. See [fiddle](https://jsfiddle.net/remarkablemark/gt8y2ksa/).

Your current solution of deleting the attribute when it is `false` is what I would do myself.

**Comment by remarkablemark** [comment] 2020-03-04 01:03
Let me know if you have any others questions. If not, feel free to close the issue.

**Closed** 2020-03-04 02:54 UTC
