### ISSUE TITLE
Parser not working in Samsung internet and KaiOS

### ISSUE THREAD

**Issue by syedfarathsayeed** [remarkablemark/html-react-parser#224] opened 2021-02-02 16:29 UTC
I am getting a `blank white screen` when trying to parse a html string in `Samsung internet or KaiOS`, but works well with chrome, safari and firefox.

Does the plugin supports these browsers?

Thanking you in advance.

**Comment by chateauvieux** [comment] 2021-02-02 21:14
getting the same issue on KaiOS 2.5, KaiOS 2.5.2, Samsung Internet 13.2.xxx
Has anybody an idea of how we can debug/diagnose the issue on those phone browsers ?

**Comment by remarkablemark** [comment] 2021-02-02 23:50
@syedfarathsayeed @chateauvieux What version of the parser are you using? Can you try downgrading to version `0.14.3`?

I unfortunately do not have access to Samsung Internet Browser or KaiOS so I am unable to test/reproduce this.

**Comment by syedfarathsayeed** [comment] 2021-02-03 00:16
I am using 1.0.0

**Comment by remarkablemark** [comment] 2021-02-03 01:59
@syedfarathsayeed Can you try downgrading to `0.14.3`? You can use TypeScript with that version as well.

**Comment by syedfarathsayeed** [comment] 2021-02-03 08:19
Yes I tried downgrading to 0.14.3, but the problem persists

**Comment by remarkablemark** [comment] 2021-02-04 04:10
Hmm... since I'm unable to reproduce this since I don't have the environment to do so, can someone help verify if the error is coming from the parser or something else?

**Comment by chateauvieux** [comment] 2021-02-13 15:45
We have fixed the problem which was not parser related. You may close this issue. Thanks

**Closed** 2021-02-13 17:07 UTC

**Comment by remarkablemark** [comment] 2021-02-13 17:28
Great to hear!
