### ISSUE TITLE
Breaks Expo

### ISSUE THREAD

**Issue by ekkis** [remarkablemark/html-react-parser#135] opened 2020-02-06 02:10 UTC
I have an expo app into which I installed this module.  mere installation seems to break the app.  I get the errors below (and many others).  what can I do?

> fontFamily "space-mono" is not a system font and has not been loaded through Font.loadAsync.
> 
> - If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
> 
> - If this is a custom font, be sure to load it with Font.loadAsync.
> - node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
> - node_modules/expo/node_modules/expo-font/build/Font.js:23:16 in processFontFamily
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:3683:38 in diffProperties
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:3557:6 in addNestedProperty
> - node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:3694:8 in diffProperties
> [...]

**Comment by remarkablemark** [comment] 2020-02-06 04:56
@ekkis Are you sure this issue is related to the parser?

This library does not load a font-family so the following error seems strange:

```
fontFamily "space-mono" is not a system font and has not been loaded through Font.loadAsync
```

**Comment by remarkablemark** [comment] 2020-02-06 20:13
Can this issue be closed as well?

**Comment by ekkis** [comment] 2020-02-07 20:56
well... it would be nice if the module worked with Expo apps.  and no, it's not related to the parser.  as I previously mentioned, merely installing it breaks the app

**Comment by remarkablemark** [comment] 2020-02-07 21:57
I see. It might be easier to debug this if you can provide a reproducible example.

**Comment by ekkis** [comment] 2020-02-07 21:57
of course.  I'll work on something for you

**Comment by remarkablemark** [comment] 2020-03-13 22:31
Closing issue due to inactivity. Feel free to reopen if you have something to add.

**Closed by remarkablemark** 2020-03-13 22:31 UTC
