### ISSUE TITLE
./node_modules/html-dom-parser/lib/client/html-to-dom.mjs Can't import the named export 'formatDOM' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Narenderb** [remarkablemark/html-react-parser#661] opened 2022-08-19 12:33 UTC
## Environment

- Version:
- Platform:
- Browser:

**Comment by remarkablemark** [comment] 2022-08-19 14:13
Duplicate of #662

**Closed by remarkablemark** 2022-08-19 14:13 UTC
