### ISSUE TITLE
Parsing correctly formatted self closing tags causes nesting bug

### ISSUE THREAD

**Issue by arriesbrendan** [remarkablemark/html-react-parser#189] opened 2020-12-11 14:50 UTC
## Description
When parsing in elements like [&lt;div /&gt;&lt;div /&gt;, &lt;path /&gt;&lt;path /&gt;, etc] causes the program to nest the elements instead of placing them as siblings.

## What should happen
html = "&lt;path /&gt;&lt;path /&gt;"
parse(html) = &lt;path /&gt;&lt;path /&gt; OR &lt;path&gt;&lt;/path&gt;&lt;path&gt;&lt;/path&gt;

## What happens instead
html = "&lt;path /&gt;&lt;path /&gt;"
parse(html) = &lt;path&gt;&lt;path&gt;&lt;path /&gt;&lt;path /&gt;

## Steps to Reproduce
Parse in any self closing tags back to back, the error doesn't happen when parsing a single tag only multiple in succession.

**Comment by remarkablemark** [comment] 2020-12-12 04:37
This is expected behavior.

You may want to check out option [`htmlparser2`](https://github.com/remarkablemark/html-react-parser/tree/v0.14.2#htmlparser2) and try enabling [`xmlMode`](https://github.com/fb55/htmlparser2/wiki/Parser-options#option-xmlmode):

```js
const parse = require('html-react-parser');

parse('<path /><path />', {
  htmlparser2: {
    decodeEntities: true,
    xmlMode: true
  }
});
```

However, note that this option is only available on the server-side (Node.js) and does not work on the client-side (browser).

See #158

**Comment by Protectator** [comment] 2020-12-28 10:10
I'm using html-react-parser on the client side. What path(s) toward supporting parsing self-closing tags on the client-side do you see ?

**Comment by remarkablemark** [comment] 2021-01-04 00:11
@Protectator There might not be an easy way to support parsing invalid self-closing tags on the client-side since we're using [html-dom-parser](https://github.com/remarkablemark/html-dom-parser), which relies on the native DOM parser.

If you're not using the `replace` option, my recommendation is to sanitize the HTML string and using React's [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml).

**Comment by remarkablemark** [comment] 2021-04-17 23:35
Closing issue due to inactivity.

**Closed by remarkablemark** 2021-04-17 23:35 UTC
Labels: question
