### ISSUE TITLE
<b> and <strong> tags are ignored

### ISSUE THREAD

**Issue by SavedByZero** [remarkablemark/html-react-parser#200] opened 2020-12-22 17:04 UTC
Is this a bug report?

* Yes: Continue filling out the template.

## Expected Behavior
The following text should appear with italics and bold when parsed with parse():

`Have you heard of Chronic Absence? <i>1 in 6 </i>students are considered <strong>chronically absent</strong>, which means they miss over 15 days of school each year. <br><br>This was before COVID-19. Now, even more children are at serious risk of falling behind in school. Should we risk their health by forcing them to attend summer school, or should we create a remote version instead?`

## Actual Behavior

The italics show up, but the bold doesn't. 

## Steps to Reproduce

Use the Poppins family font, ttf. Make sure all the styles (light, regular, bold, etc.) are in  your fonts folder.  Pull css only from the main App.css file.  Use   var parse = require('html-react-parser') at the top of your render function, then `<div>{parse(yourText)}</div>`

## Environment

1.0.0
iOS Safari 
PC Edge

**Comment by remarkablemark** [comment] 2020-12-23 02:22
Can you provide a reproducible example on [CodeSandbox](https://codesandbox.io/s/940pov1l4w) or [JSFiddle](https://jsfiddle.net/remarkablemark/7v86d800/)?

**Comment by SavedByZero** [comment] 2021-03-04 16:59
Sorry it took me so long to get back to this. I am trying to make up an example now, but I noticed that I'm getting "parse is not a function" errors with the latest version.

**Comment by SavedByZero** [comment] 2021-03-04 18:00
scratch that, I got it to work by using the import method instead of the require method. Anyhow, here's a test example that replicated the issue on _some_ browsers: 

https://codesandbox.io/s/eloquent-sara-stiis?file=/src/App.js

In Firefox, the bold doesn't show up, but if you change it to italics, the italics show.  Chrome seems to work okay though, for some reason.

**Comment by remarkablemark** [comment] 2021-03-09 02:13
@SavedByZero Thanks for creating the CodeSandbox example, I believe the `font-weight` is not rendering correctly because the [Poppins](https://fonts.google.com/specimen/Poppins) font-family is not loaded and you may be using the incorrect font-weight. By default, if the font is not loaded correctly, the browser will fallback to a default font.

**Comment by remarkablemark** [comment] 2021-08-11 00:31
@SavedByZero I took a look at your [CodeSandbox](https://codesandbox.io/s/eloquent-sara-stiis?file=/src/App.js) and it seems like the bold element is rendering correctly?

If that's the case, then I believe everything is working as expected and I'll be closing the issue.

Feel free to reopen if there's anything else you'd like to bring up.

**Closed by remarkablemark** 2021-08-11 00:31 UTC
