### ISSUE TITLE
SVG paring fails with an embedded script tag

### ISSUE THREAD

**Issue by ianbale** [remarkablemark/html-react-parser#88] opened 2019-01-10 16:04 UTC
This is a simplified copy of my SVG. I've removed a lot of the text / use statements to keep it a reasonable length.

`<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" id="carriageLayout0065" contentScriptType="text/ecmascript" contentStyleType="text/css" width="915" height="270" zoomAndPan="magnify" preserveAspectRatio="xMidYMid meet" version="1.0">
	<style><![CDATA[    text    {      font-family : Sans-Serif;      font-size :  13px;    }    .outline    {      fill:#ECEFF1;       stroke:black;    }    .seat    {      fill:#D84315;    }    .available    {      fill:#B0BEC5;          }    .priority.available    {      fill:#F8BBD0;    }    .companion.available    {      fill:#F8BBD0;    }    .wheelchair.available    {      fill:#F8BBD0;        }        .selected.available    {      fill:#8BC34A;    }    use.available    {      cursor : pointer;    }    text    {      pointer-events: none;    }    .table    {      fill:#37474F;          }    .luggage    {      fill:#BCAAA4;    }    #suitcase    {      fill : black;    }    .berth    {      stroke : black;      fill : none;    }    .bed    {      stroke : black;    }  ]]></style>
	<defs>
		<g id="fseat">
			<rect x="0" y="0" class="bg" style="stroke:none" width="35" height="37" rx="7" ry="7"/>
			<rect x="1" y="5" style="fill:black;stroke:black;opacity:0.35;" width="5" height="27" rx="2" ry="2"/>
			<rect x="8" y="1" style="fill:black;stroke:black;opacity:0.35;" width="20" height="5" rx="2" ry="2"/>
			<rect x="8" y="30" style="fill:black;stroke:black;opacity:0.35;" width="20" height="5" rx="2" ry="2"/>
		</g>
		<g id="bseat">
			<rect x="0" y="0" class="bg" style="stroke:none" width="35" height="37" rx="7" ry="7"/>
			<rect x="30" y="5" style="fill:black;stroke:black;opacity:0.35;" width="5" height="27" rx="2" ry="2"/>
			<rect x="8" y="1" style="fill:black;stroke:black;opacity:0.35;" width="20" height="5" rx="2" ry="2"/>
			<rect x="8" y="30" style="fill:black;stroke:black;opacity:0.35;" width="20" height="5" rx="2" ry="2"/>
		</g>
		<g id="sfseat">
			<rect x="0" y="0" class="bg" style="stroke:none" width="30" height="37" rx="7" ry="7"/>
			<rect x="1" y="5" style="fill:black;stroke:black;opacity:0.35;" width="5" height="27" rx="2" ry="2"/>
			<rect x="8" y="1" style="fill:black;stroke:black;opacity:0.35;" width="15" height="5" rx="2" ry="2"/>
			<rect x="8" y="30" style="fill:black;stroke:black;opacity:0.35;" width="15" height="5" rx="2" ry="2"/>
		</g>
		<g id="sbseat">
			<rect x="0" y="0" class="bg" style="stroke:none" width="30" height="37" rx="7" ry="7"/>
			<rect x="25" y="5" style="fill:black;stroke:black;opacity:0.35;" width="5" height="27" rx="2" ry="2"/>
			<rect x="8" y="1" style="fill:black;stroke:black;opacity:0.35;" width="15" height="5" rx="2" ry="2"/>
			<rect x="8" y="30" style="fill:black;stroke:black;opacity:0.35;" width="15" height="5" rx="2" ry="2"/>
		</g>
		<g id="lfseat">
			<rect x="0" y="0" class="bg" style="stroke:none" width="40" height="37" rx="7" ry="7"/>
			<rect x="1" y="5" style="fill:black;stroke:black;opacity:0.35;" width="5" height="27" rx="2" ry="2"/>
			<rect x="8" y="1" style="fill:black;stroke:black;opacity:0.35;" width="25" height="5" rx="2" ry="2"/>
			<rect x="8" y="30" style="fill:black;stroke:black;opacity:0.35;" width="25" height="5" rx="2" ry="2"/>
		</g>
		<g id="lbseat">
			<rect x="0" y="0" class="bg" style="stroke:none" width="40" height="37" rx="7" ry="7"/>
			<rect x="35" y="5" style="fill:black;stroke:black;opacity:0.35;" width="5" height="27" rx="2" ry="2"/>
			<rect x="8" y="1" style="fill:black;stroke:black;opacity:0.35;" width="25" height="5" rx="2" ry="2"/>
			<rect x="8" y="30" style="fill:black;stroke:black;opacity:0.35;" width="25" height="5" rx="2" ry="2"/>
		</g>
		<g id="sberth">
			<rect x="0" y="0" width="90" height="190" class="berth"/>
		</g>
		<g id="dberth">
			<rect x="0" y="0" width="90" height="190" class="berth"/>
		</g>
		<g id="mbed">
			<rect x="0" y="0" width="70" height="40" class="bed bg"/>
		</g>
		<g id="wchair" transform="scale(0.05)">
			<rect width="570" height="720" x="20" y="0" rx="60" ry="60" stroke="none" class="bg"/>
			<path transform="translate(60,80)" fill="black" fill-rule="evenodd" clip-rule="evenodd" d="M161.9882813,98.1240234&#10;        c24.9628906-2.3046875,44.3574219-23.8110352,44.3574219-48.9658203C206.3457031,22.0830078,184.2626953,0,157.1875,0&#10;        s-49.1572266,22.0830078-49.1572266,49.1582031c0,8.2568359,2.3037109,16.7055664,6.1445313,23.8105469l17.515625,246.4667969&#10;        l180.3964844,0.0488281l73.9912109,173.3652344l97.1445313-38.0976563l-15.0429688-35.8203125l-54.3662109,19.625&#10;        l-71.5908203-165.2802734l-167.7294922,1.1269531l-2.3027344-31.2128906l121.4228516,0.0483398v-46.1831055l-126.0546875-0.0493164&#10;        L161.9882813,98.1240234z"/>
			<path transform="translate(60,80)" fill="black" fill-rule="evenodd" clip-rule="evenodd" d="M343.4199219,451.5908203&#10;        c-30.4472656,60.1875-94.1748047,99.8398438-162.1503906,99.8398438C81.4296875,551.4306641,0,470.0009766,0,370.1611328&#10;        c0-70.1005859,42.4853516-135.2436523,105.8818359-164.1210938l4.1025391,53.5375977&#10;        c-37.4970703,23.628418-60.6123047,66.262207-60.6123047,110.9506836c0,72.4267578,59.0712891,131.4970703,131.4970703,131.4970703&#10;        c66.2617188,0,122.7646484-50.8515625,130.4697266-116.0869141L343.4199219,451.5908203z"/>
		</g>
		<g id="suitcase" transform="scale(0.1)">
			<g transform="translate(30,-65)">
				<rect x="48" y="32" width="144" height="160"/>
				<path style="fill:black" d="m  40,32 0,160 -16,0 a  24,24 0 0 1 -24,-24 l 0,-112 a  24,24 0 0 1  24,-24 z"/>
				<path d="m 200,32 16,0 a  24,24 0 0 1  24,24  l 0,112 a  24,24 0 0 1 -24,24  l -16,0 z"/>
				<path d="m  84,30 0,-12 a  18,18 0 0 1 18,-18 l 36,0 a  18,18 0 0 1 18,18  l 0,12 -12,0 0,-12 a   6,6  0 0 0 -6,-6  l -36,0 a   6,6  0 0 0 -6,6   l 0,12 z"/>
			</g>
		</g>
	</defs>
	<rect x="10" y="10" width="893" height="195" class="outline"/>
	<rect x="106" y="20" width="25" height="60" class="table"/>
	<rect x="106" y="20" width="25" height="60" class="table"/>
	<rect x="106" y="20" width="25" height="60" class="table"/>
	<use xmlns:xlink="http://www.w3.org/1999/xlink" id="PL-61A" x="40" y="14" xlink:type="simple" xlink:actuate="onRequest" xlink:show="replace" xlink:href="#sbseat" class="seat"/>
	<use xmlns:xlink="http://www.w3.org/1999/xlink" id="PL-60A" x="40" y="52" xlink:type="simple" xlink:actuate="onRequest" xlink:show="replace" xlink:href="#sbseat" class="seat"/>
	<use xmlns:xlink="http://www.w3.org/1999/xlink" id="PL-57A" x="73" y="14" xlink:type="simple" xlink:actuate="onRequest" xlink:show="replace" xlink:href="#sfseat" class="seat"/>
	<use xmlns:xlink="http://www.w3.org/1999/xlink" id="PL-55A" x="134" y="14" xlink:type="simple" xlink:actuate="onRequest" xlink:show="replace" xlink:href="#sbseat" class="seat"/>
	<use xmlns:xlink="http://www.w3.org/1999/xlink" id="PL-56A" x="73" y="52" xlink:type="simple" xlink:actuate="onRequest" xlink:show="replace" xlink:href="#sfseat" class="seat"/>
	<use xmlns:xlink="http://www.w3.org/1999/xlink" id="PL-54A" x="134" y="52" xlink:type="simple" xlink:actuate="onRequest" xlink:show="replace" xlink:href="#sbseat" class="seat"/>
	<use xmlns:xlink="http://www.w3.org/1999/xlink" id="PL-49A" x="196" y="14" xlink:type="simple" xlink:actuate="onRequest" xlink:show="replace" xlink:href="#sbseat" class="seat"/>
	<text x="44" y="37">61A</text>
	<text x="44" y="75">60A</text>
	<text x="77" y="37">57A</text>
	<text x="138" y="37">55A</text>
	<text x="77" y="75">56A</text>
	<text x="138" y="75">54A</text>
	<script><![CDATA[  var svgDoc = document.getElementById('carriageLayout0065');      var selector = '[id^=' + String.fromCharCode(039) + 'PL-' + String.fromCharCode(039) + ']';  var ids = svgDoc.querySelectorAll(selector);      for (var x=0;x<ids.length;x++)      {          if (ids[x].classList.contains('available'))          {              ids[x].addEventListener('click',function(event){                          if (top.toggleSeat(event))        {          event.target.classList.toggle('selected');         }      })          }      }   ]]></script>
</svg>
`

This results in the following error:

SyntaxError: Unexpected end of input
appendChild
node_modules/react-dom/cjs/react-dom.development.js:8701
  8698 | }
  8699 | 
  8700 | function appendChild(parentInstance, child) {
> 8701 |   parentInstance.appendChild(child);
  8702 | }
  8703 | 
  8704 | function appendChildToContainer(container, child) {
View compiled
commitPlacement
node_modules/react-dom/cjs/react-dom.development.js:15066
  15063 |     if (isContainer) {
  15064 |       appendChildToContainer(parent, node.stateNode);
  15065 |     } else {
> 15066 |       appendChild(parent, node.stateNode);
  15067 |     }
  15068 |   }
  15069 | } else if (node.tag === HostPortal) {
View compiled
commitAllHostEffects
node_modules/react-dom/cjs/react-dom.development.js:15822
  15819 | switch (primaryEffectTag) {
  15820 |   case Placement:
  15821 |     {
> 15822 |       commitPlacement(nextEffect);
  15823 |       // Clear the "placement" from effect tag so that we know that this is inserted, before
  15824 |       // any life-cycles like componentDidMount gets called.
  15825 |       // TODO: findDOMNode doesn't rely on this any more but isMounted
View compiled

If I remove the script then it works as expected. 

{ParseHTML(svgString.replace(/<\/?script[^>]*/g,''))}

**Comment by ianbale** [comment] 2019-01-10 16:07
Also I have noticed that contentScriptType and contentStyleType in the SVG tag are being replaced with lower case version which results in this warning in the browser:

index.js:2178 Warning: Invalid DOM property `contentscripttype`. Did you mean `contentScriptType`?
    in svg (created by Coach)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (at coach.js:148)
    in Coach (created by WithStyles(Coach))
    in WithStyles(Coach) (created by Route)
    in Route (at App.js:109)
    in div (at App.js:80)
    in div (at App.js:63)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:61)
    in App (at src/index.js:7)

**Comment by ianbale** [comment] 2019-01-10 20:45
Looking a little deeper I am pretty sure that (var x=0;x<ids.length;x++) is causing the problem. It looks like the parser is dying when its hits the <

Since the script tag's content is in a CDATA element, it should not have a problem with this.

I've also tried react-render-html which has the exact same problem, so my assumption is that the problem is in one of the dependencies.

**Comment by remarkablemark** [comment] 2019-01-11 01:13
@ianbale Can you help me reproduce the error you're seeing with [JSFiddle](https://jsfiddle.net/remarkablemark/7v86d800/) or [CodeSandbox](https://codesandbox.io/s/940pov1l4w)?

**Comment by ianbale** [comment] 2019-01-22 10:34
Since the script is essential, rendering without it is not really an option, neither is changing the input SVG.

Surely the parser should handle CDATA since it's a perfectly valid within the XML?

For now I'm just using dangerouslySetInnerHTML which works perfectly. Since it's a private app with trusted SVG data that is not a problem for me.

**Comment by remarkablemark** [comment] 2019-01-23 00:43
Gotcha. Technically, the parser should handle the CDATA but it seems like it didn't in my example. I think using `dangerouslySetInnerHTML` should be fine in your use case.

If the issue is resolved on your end, do you mind closing it?

**Comment by ianbale** [comment] 2019-01-23 23:16
I could... but having decided to use dangerouslySetInnerHTML before I even reported the issue to you, the whole point of doing so was to give you the heads up so this issue,  which is bound to affect someone else at some point, could be resolved.

As I mentioned, I think it is likely that the fault does not lie in html-react-parser, but rather in one your of dependencies. It might be nice if you could locate the offending one and pass the issue onto them rather then just closing this one...

I'm happy to do that if you can tell me which one is causing the problem?

**Comment by remarkablemark** [comment] 2019-01-24 00:31
I understand and appreciate your sentiment. The bug may be coming from [`html-dom-parser`](https://github.com/remarkablemark/html-dom-parser).

It would be nice to create a simplified test case that reproduces this bug in the other package.

**Comment by ianbale** [comment] 2019-02-11 17:01
Thanks. I'll raise an issue there as soon as I have a few spare minutes.

**Comment by remarkablemark** [comment] 2019-08-26 01:24
Closing issue due to inactivity. Feel free to reopen if there are new updates.

**Closed by remarkablemark** 2019-08-26 01:24 UTC
Labels: question
